pipeline {
      agent any
      stages {
          stage('Checkout') {
              steps {
                  git branch: 'master',
                      url: 'https://gitlab.com/assistiverobot/assistiverobot.web.service.git'
                  echo 'Checkout complete'
              }
          }
          stage('Build') {
              steps {
                  bat 'dotnet build AssistiveRobot.Web.Service.sln'
              }
          }
          stage('Deploy') {
              steps {
                  bat 'appcmd stop apppool /apppool.name:\"Toktak Web Service\"'
                  bat label: '', script: '''cd ./AssistiveRobot.Web.Service
                                         dotnet restore
                                         dotnet publish --configuration Release --output D:\\Toktak-Web-Service\\production'''
                  bat 'appcmd start apppool /apppool.name:\"Toktak Web Service\"'
              }
          }
      }
}